security:
    oauth2:
      client:
        clientId: ''
        clientSecret: ''
        accessTokenUri: 'https://github.com/login/oauth/access_token'
        userAuthorizationUri: 'https://github.com/login/oauth/authorize'
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        registered-redirect-uri:
        - 'http://localhost:8080'
        pre-established-redirect-uri: 'http://localhost:8080/index.html'
      resource:
        userInfoUri: 'https://api.github.com/user'
          